{{- if not .Values.gateway.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conduit.fullname" . }}
  labels:
    {{- include "conduit.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.gateway.adminKey }}
  admin-key: {{ .Values.gateway.adminKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.apiKeys }}
  api-keys: {{ .Values.auth.apiKeys | join "," | b64enc | quote }}
  {{- end }}
{{- end }}
